### ISSUE TITLE
Integrate with ON

### ISSUE THREAD

**Issue by joaodealmeida** [arcbtc/flux-capacitor#1]
Hey, would you be cool if I did a PR to integrate this with the OpenNode (https://opennode.co/docs) API ?

**Comment by arcbtc** [comment]
Dude, do what you want. Will be making a video tutorial for it next week. If there is anything else I can do to help just ask

**Comment by arcbtc** [comment]
So you know will also be adding an access point feature next week, making it really easy to add WiFI and API credentials, and will also add currency conversion

**Comment by joaodealmeida** [comment]
ok, i will wait for that PR first

**Comment by arcbtc** [comment]
Got there in the end!
https://github.com/arcbtc/flux-capacitor/tree/master/ONversion
