### ISSUE TITLE
How do I plug with E-Paper?

### ISSUE THREAD

**Issue by NicolasDorier** [arcbtc/flux-capacitor#2]
There is no "MISO" or "MOSI" named pin on the epaper...

**Comment by arcbtc** [comment]
Yikes sorry. If you're using the MH-ET-LIVE epaper I have added a GPIO mapping table. I have also completed a more up to date version which uses OpenNode:

https://github.com/arcbtc/flux-capacitor/tree/master/ONversion 

I will be releasing a video tutorial in a few hours for it.

**Comment by NicolasDorier** [comment]
cool!
